# Dataset / Model parameters
data_dir: ./data/cifar10-dvs-tet
dataset: cifar10-dvs-tet
pretrained: False
num_classes: 10
num_heads: 16
img_size: 128
crop_pct: 1.0
scale:
    - 1.0
    - 1.0
ratio: [1.0, 1.0]
color_jitter: 0.
interpolation: bicubic
train_interpolation: bicubic
use_conv_as_linear: true
pooling_stat: "0111"
in_channels: 2
time_steps: 10
layer: 2
dim: 256
mlp-ratio: 4

# Model Exponential Moving Average
model-ema: False
model-ema-decay: 0.9998

# Misc
seed: 42
amp: True
channels-last: False
batch_size: 16
val_batch_size: 16
lr: 1e-3
min_lr: 1e-5
sched: cosine
weight_decay: 1e-4
decay_epochs: 20
epochs: 96
cooldown_epochs: 10
warmup_epochs: 10
warmup_lr: 1e-5
opt: lamb
smoothing: 0.1
workers: 8
