mask_ratio: 0.75
train_split_path: ./train_idx.npy

# Dataset / Model parameters
data_dir: /data1/ligq/imagenet1-k
dataset: imagenet
pretrained: False
num_classes: 1000
num_heads: 8
img_size: 224
mean:
    - 0.485
    - 0.456
    - 0.406
std:
    - 0.229
    - 0.224
    - 0.225
crop_pct: 1.0
scale:
    - 0.2
    - 1.0
interpolation: bicubic
train_interpolation: bicubic
pooling_stat: "1111"
use_conv_as_linear: true
time_steps: 4
layer: 8
dim: 768
mlp-ratio: 4

# Augmentation & regularization parameters
aa: rand-m7-mstd0.5-inc1
mixup: 0.2
mixup_off_epoch: 0
mixup_prob: 1.0
mixup_mode: batch
mixup_switch_prob: 0.5
cutmix: 1.0

# Model Exponential Moving Average
model_ema: False
model_ema_decay: 0.9998

# Misc
seed: 42
amp: True
channels_last: False
batch_size: 20
val_batch_size: 20
lr: 1e-3
min_lr: 1e-5
sched: cosine
weight_decay: 1e-2
epochs: 400
cooldown_epochs: 10
warmup_epochs: 20
warmup_lr: 1e-5
opt: lamb
smoothing: 0.1
workers: 8
